### ISSUE TITLE
Missing language strings/ references for translation

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#347]
Hello!
I am working on the german translation as you can see here:
https://steamcommunity.com/sharedfiles/filedetails/?id=3201487871

Sadly, some text can not be translated because of missing text inside the original text files.
Can you help or add the missing ones?

Here are the ones i have noticed:

1.
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/617f5bea-5674-425f-a65a-dce55a5f564c)
2.
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/6d9ce69d-375b-4a71-8014-9365ee074858)
3.
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/e4aea7c4-bea0-4525-b6e4-43fecca8fbc9)
4.
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/e27db753-2d3a-40d2-a95c-a85aea663e34)
5.
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/b8a3d4ed-41e9-4a2b-93c3-b9d4a9c8fc9e)
6.
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/2bca8f8c-7876-4721-a1d9-6a30eb7bd5b4)
7. developer console
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/1ed0447d-a8d4-45bd-b9db-58187f48887b)
8. developer console
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/30c8c0e1-eae6-4380-b91f-aa5948dbe286)
9.
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/92c8d3ec-9ebe-4f80-a4a1-14a2ad1ad8db)

10. uploading a mod:
![firefox_DzS3fZQYuz](https://github.com/LorisYounger/VPet/assets/155199582/b4e8e034-6ef6-4ba9-a4a3-7c41ddd0b1a6)

11. Some loading messages (language was set to chinese):
![NVIDIA_Share_iIyk5EvuPS-ezgif com-resize](https://github.com/LorisYounger/VPet/assets/155199582/7617d915-b19c-469b-b4d9-b021a4e61fa8)

12. Missing tooltip (hint) for two options. the same is used 3 times.
![NVIDIA_Share_AovwAWWXco](https://github.com/LorisYounger/VPet/assets/155199582/a785b977-3a47-485f-8f04-e6d597d4e2f9)

13. hint missing (text and hint use the same text):
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/abe2c17d-5844-43a3-8a50-d32f70db4f06)

14. hint missing (text and hint use the same text):
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/52c201d1-9e89-41ab-9920-2b9484087b46)

15. hint missing
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/eb0066e7-ea38-4153-928b-e9bf567b99cd)

16. language name
There is no translation for translation language.
"de" in this example case is used from the folder name inside /lang/.
I would like to translate it with:
%foldername%#my text:|
Also there is a "null" entry inside the language dropdown?
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/ade126c3-69d1-4cd8-b8e8-218c59dfe592)

17. missing window name in every language
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/125cfea4-aace-43b1-a38b-e60580fb79dd)

18.  missing window name in every languange (mod maker)
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/fb016998-486e-4053-854b-3aec246abf15)

19. missing window name in every languange (mod maker)
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/ecf679ea-5b43-4bd4-8556-bd098210f671)

20.  missing window name in every languange (mod maker)
![grafik](https://github.com/LorisYounger/VPet/assets/155199582/ec837ad1-ffc6-42fc-b2b8-f2ffaf818fa8)

**Comment by LorisYounger** [comment]
1. This is set to English by default, and we feel that there is no need for translation, so we did not make it
2. Fixed
3. This defaults to English, preventing players from accidentally switching to other languages they don't understand, and allowing them to find the location to change the language
4. Fixed
5. Fixed
6. Fixed
7. Fixed
8. Fixed
9. Because the text contains double quotation marks, it was not detected by the translation detection tool I wrote. The translation was missed, not because the translation system did not work. It has been completed
10. Fixed
11. The initial loading text cannot be translated because the translation file has not been loaded. I use English as a substitute
12. Fixed
13. Because these texts are very intuitive, I didn't think of a good introduction, so I used the same text
14. Same, What's different is that, the UI is not fully displayed here due to the length of the English text, and a short translation is used instead
15. There will be no introduction here, as this is text provided by the mod. The settings vary depending on the mod, and the mod settings should be used as the standard
If here use the default select to speak, this button is actually fake and has no function (lol)
16. Because for versatility, the translation language nae used for the VPet is CultureInfo, which can support the parent class to search for the translated content, such as `en-us` -> `en`,  `zh-HK` -> `zh-Hant`
https://learn.microsoft.com/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c
I am considering providing translations for the headers of translated text, but I am still in the process of making a decision. If you feel that providing translations for translated file names is beneficial, you can raise an issue
17-20. I will confirm again when I deal with the MODMaker later

**Comment by LorisYounger** [comment]
6. This uses the built-in features of the UI library. I'm not sure where to modify the translation content, but this should be automatically adapted by the system, so I think you shouldn't have to worry about it.
By the way, I will ask the author of this beautiful UI library for you. @Mochengvia 

7. I missed this. However, I remember there is a bug in this function of the dev window, which may cause some problems when using it. I will add it when I fix the bug

**Comment by LorisYounger** [comment]
17-20 There is no title because there is no need, so there is no need to add additional text that needs to be translated
After my inspection, the responses of the MOD maker have been basically translated, if there are any omissions, please let me know
Fixed a large number of bugs and the latest mod maker 1.10.10 will be released tonight

**Comment by LorisYounger** [comment]
I think the problems here have been fully resolved. If there are any remaining issues, please leave a comment and at me, and I will reopen it

**Comment by LorisYounger** [comment]
This uses the built-in features of the UI library. I'm not sure where to modify the translation content, but this should be automatically adapted by the system, so I think you shouldn't have to worry about it. @Mochengvia
If you have an English system but it still shows `确定`, this can be considered a bug in the UI library, and I will issue an issue on the corresponding project

**Comment by LorisYounger** [comment]
I communicated with the UI author and found out that in the latest version, the translation of the message window has been cancelled, and now the author needs to manually translate it
now fix in https://github.com/LorisYounger/VPet/commit/1745a8f3519dec5312b114f41c0a8170f1d57b92
