### ISSUE TITLE
Schedule resting can be abused (bug)

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#390]
Hey there!

While creating a translation i have tested the new feature called "Schedules".
There is a need for resting time inside the schedule but you can have it all at the **END** of it (see screenshot).
If you can use as many events as you like while doing this tactic the system can be abused and the rest time is obsolete.

![grafik](https://github.com/LorisYounger/VPet/assets/155199582/84385850-e06d-48c5-ae82-75bf24130877)

Suggestion:
no resting time useable after the last event in schedule

**Comment by LorisYounger** [comment]
This is difficult to control, because even if you don't allow breaks at the end, stopping during the middle of the break is the same. So there's no way to fix it.
In fact, the Schedule is designed to work automatically and reduce the amount of operation. If players have to manually stop every time, it is actually more convenient to use the work function directly
So I think we don't need to worry about it
