### ISSUE TITLE
Schedule can be edited while in progress (bug)

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#392]
Hey there!

When a schedule is in progress/ started you can edit the schedule. For exmaple delete all resting time (see screenshot).
In this example it is against the rule of resting time but i could lead to other problems, too.

![grafik](https://github.com/LorisYounger/VPet/assets/155199582/f97502d2-30c2-44ea-b0fb-1eda4095e624)

**Suggestion:**
When schedule is started, editing the schedule is not possible.

**Comment by LorisYounger** [comment]
This is difficult to control, because even if you don't allow breaks at the end, stopping during the middle of the break is the same. So there's no way to fix it.
In fact, the Schedule is designed to work automatically and reduce the amount of operation. If players have to manually stop every time, it is actually more convenient to use the work function directly
So I think we don't need to worry about it
