### ISSUE TITLE
Clicking on body does not trigger speaking (like in tutorial description)

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#399]
Hey there!

I have noticed a possible bug. When in idle and clicking (left click) on body does not trigger an answer.
Instead an animation (touch body) is triggered. Sometimes it works but rarely.

I took a look into the tutorial and it states an other behaviour. When there is only a chance for speaking maybe add this information in the tutorial.

![grafik](https://github.com/LorisYounger/VPet/assets/155199582/1f18e3a5-7988-4e97-aa10-afa81d876afb)

**Comment by LorisYounger** [comment]
Because you clicked on the location of touch body, not the location of speaking
You can click on the corners (such as the upper left corner/lower right corner) to trigger the speech
Because speaking is the lowest priority. Except for touching the head, body and face, all the remaining parts are for talking.

**Comment by LorisYounger** [comment]
Updated tutorials and introductions are planned
