### ISSUE TITLE
photo gallery missing info at unlocked elements

### ISSUE THREAD

**Issue by j6845** [LorisYounger/VPet#432]
Hello there!
When you have unlocked a photo, you can click on it to see the details.
There are the following informations:
1. Name
2. Unlocked at date and time
3. Description

What i am missing here is this information:
4. Requirements for the unlock
5. Unlocked with money? yes/ no

![grafik](https://github.com/user-attachments/assets/88fa7490-51af-4d6e-9596-ec4892477e90)

**Comment by LorisYounger** [comment]
I have no intention of considering whether to pay to unlock or unlock information for the time being
because
It seems unnecessary to retain the unlocking information after it has been unlocked
Currently, there is no record of whether money was spent to unlock it
If you find these two pieces of information to be highly necessary, feel free to discuss
