### ISSUE TITLE
[Advice] Define constant data with flatbuffer or json

### ISSUE THREAD

**Issue by hax0r31337** [LorisYounger/VPet#64]
I'm working on port this minigame to Linux, and during the process, I've noticed that this game utilizes an [outdated format](https://github.com/LorisYounger/VPet/blob/main/VPet-Simulator.Windows/mod/0000_core/food/food.lps) for its constant definitions.   
I **strongly recommend** transition to [FlatBuffers](https://flatbuffers.dev/) or, if human-readability is necessary, to JSON

**Comment by LorisYounger** [comment]
Thank you for your support of this project. It's great to hear about the migration of Linux.
Although switching to JSON has significant benefits, due to historical legacy reasons and my personal development preferences, the project will not be transferred to JSON.
I have asked my developer to start developing the vscode plugin to make this format easier to read, Including completion and alignment.
For programmers, there is a very user-friendly C # class library that can be easily read and written. https://github.com/LorisYounger/LinePutScript
I apologize for my capriciousness :|

**Comment by mahdiyari** [comment]
@hax0r31337 Is your work public?

**Comment by hax0r31337** [comment]
> @hax0r31337 Is your work public?

Nope it's intended private use, I've changed some features in the game, and lot's of feature missing, so I can't say it's a Linux port

**Comment by mahdiyari** [comment]
> Nope it's intended private use, I've changed some features in the game, and lot's of feature missing, so I can't say it's a Linux port

I would take any linux version over nothing but I get it. Thanks for replying.
